version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-west-2:618889059366:task-definition/pastel-notes-task:4"
        LoadBalancerInfo:
          ContainerName: "pastel-notes-app"
          ContainerPort: 3000